spring:
  application:
    name: legacy-loan-event-service
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest  
security:
  basic:
    enabled: false
deep:
  env: development
  consumerName: aggregation-handler-retry
  rules:
    uri: http://deep-rules-development.dev.px-01.cf.t-mobile.com
logging:
  level:
    root: INFO
logging.queue name: promotion.inter.domain.log
logging.topic name: pde-deep-event-log
promo.decision.queue: promotion.decision.evaluation
promo.decision.topic: pde-promo-decision-evaluation
server.port: 9000
legacy:
 loan:
  create:
    event:
     listener: false
